from typing import Protocol
from .models import Candle
class MarketDataGateway(Protocol):
 def connection_state(self)->dict:...
 def closed_candles(self,symbol:str,timeframe:str,count:int)->list[Candle]:...
 def latest_tick(self,symbol:str)->dict:...
class MarketDataUnavailable(RuntimeError): pass
