from enum import StrEnum
class TenantStatus(StrEnum): ACTIVE='ACTIVE'; SUSPENDED='SUSPENDED'
class UserStatus(StrEnum): ACTIVE='ACTIVE'; SUSPENDED='SUSPENDED'; INVITED='INVITED'
class AccountEnvironment(StrEnum): DEMO='DEMO'; LIVE='LIVE'; PROP_FIRM='PROP_FIRM'
class ConnectionStatus(StrEnum): DISCONNECTED='DISCONNECTED'; CONNECTING='CONNECTING'; CONNECTED='CONNECTED'; DEGRADED='DEGRADED'; STALE='STALE'; ERROR='ERROR'
class SystemMode(StrEnum): ANALYSIS_ONLY='ANALYSIS_ONLY'; SHADOW='SHADOW'; DEMO_AUTONOMOUS='DEMO_AUTONOMOUS'; LIVE_AUTONOMOUS='LIVE_AUTONOMOUS'; PAUSED='PAUSED'; EMERGENCY_STOP='EMERGENCY_STOP'
